cmake_minimum_required(VERSION 3.10)
project(Autopilot)
set(CMAKE_CXX_STANDARD 17)
add_executable(autopilot src/autopilot.cpp)
find_package(CURL REQUIRED)
include_directories(include)
target_include_directories(autopilot PRIVATE ${CURL_INCLUDE_DIRS})
target_link_libraries(autopilot PRIVATE ${CURL_LIBRARIES})
